services:
  app:
    build:
      context: .
    container_name: fastapi-app-gemini-gateway
    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy-gemini-gateway
    ports:
      - "8000:80"
    depends_on:
      - app
    restart: unless-stopped
