services:
  app:
    build:
      context: .
    container_name: fastapi-app
    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
